---
- name: Gather facts from all servers
  hosts: cisco
  gather_facts: no   # skip default OS facts
  connection: network_cli
  tasks:
    - name: Gather IOS facts
      cisco.ios.ios_facts:

    - name: Show hostname
      debug:
        msg: "Hostname: {{ ios_facts.net_hostname }}"

    - name: Show IOS version
      debug:
        msg: "Version: {{ ios_facts.version }}"