---
- name: Gather facts from all servers
  hosts: cisco
  gather_facts: no   # skip default OS facts
  connection: network_cli
  tasks:
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Show hostname
      debug:
        msg: "Hostname: {{ ansible_net_hostname }}"

    - name: Show IOS version
      debug:
        msg: "Version: {{ ansible_net_version }}"
    
    - name: Show Model
      debug:
        msg: "Model: {{ ansible_net_model }}"
