---
- name: Gather facts from all servers
  cisco.ios.ios_facts:
    gather_subset: all
- name: Show hostname
  debug:
    msg: 
      - "Hostname: {{ ansible_net_hostname }}"
      - "Version: {{ ansible_net_version }}"
      - "Model: {{ ansible_net_model }}"