---
- name: Gather facts from all servers
  hosts: cisco
  gather_facts: yes
  tasks:
    - name: Display all facts
      debug:
        var: ansible_facts
        msg: "This host {{inventory_hostname}} has hostname {{ ansible_facts['hostname'] }}"