---
- name: Gather facts from all servers
  hosts: cisco
  gather_facts: no   # skip default OS facts
  connection: network_cli
  tasks:
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Show hostname
      debug:
        msg: 
          - "Hostname: {{ ansible_net_hostname }}"
          - "Version: {{ ansible_net_version }}"
          - "Model: {{ ansible_net_model }}"